ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    name: codespell (add false positives to pyproject.toml)
    args: [--write-changes]
    additional_dependencies:
    - tomli
