ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    name: codespell (add false positives to pyproject.toml)
    args: [--write-changes]
    exclude: "2024-LLE/single_particle_drifts.ipynb"
    additional_dependencies:
    - tomli
