ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
    name: check for git merge conflicts
    exclude: .*\.rst
  - id: check-case-conflict
    name: check for filename case conflicts
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-toml
  - id: check-yaml

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    name: codespell (add false positives to pyproject.toml)
    args: [--write-changes]
    exclude: "2024-LLE/single_particle_drifts.ipynb"
    additional_dependencies:
    - tomli
